name: Deploy Angular App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          # Optional, will use the specified branch. Defaults to all branches
          branch: main
          name: pmb-artifacts
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: pmb-artifacts

      - name: SCP Command to Transfer Files
        # You may pin to the exact commit or the version.
        # uses: appleboy/scp-action@8a92fcdb1eb4ffbf538b2fa286739760aac8a95b
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          # ssh port
          port: ${{ secrets.DESTINATION_PORT }}
          # ssh username
          username: ${{ secrets.DEPLOYER_USER }}
          # ssh password
          password: ${{ secrets.DEPLOYER_PW }}
          source: pmb-artifacts
          target: ${{ secrets.DESTINATION_TMP_DIR }}
      - name: Deploy app bits
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          # ssh port
          port: ${{ secrets.DESTINATION_PORT }}
          # ssh username
          username: ${{ secrets.DEPLOYER_USER }}
          # ssh password
          password: ${{ secrets.DEPLOYER_PW }}
          script_stop: true
          script: |
            rm -rfv ${{ secrets.DESTINATION_DIR }}/pmb/pmb-app/*
            cp -r -f ${{ secrets.DESTINATION_TMP_DIR }}/pmb-artifacts/personal-monthly-budget/browser/* ${{ secrets.DESTINATION_DIR }}/pmb/pmb-app
