name: Deploy Angular App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: pmb-artifacts
          path: pmb-artifacts
          
      - name: SCP Command to Transfer Files
        # You may pin to the exact commit or the version.
        # uses: appleboy/scp-action@8a92fcdb1eb4ffbf538b2fa286739760aac8a95b
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          # ssh port
          port: ${{ secrets.DESTINATION_PORT }}
          # ssh username
          username: ${{ secrets.DEPLOYER_USER }}
          # ssh password
          password: ${{ secrets.DEPLOYER_PW }}
          source: snarbank-artifacts
          target: ${{ secrets.DESTINATION_TMP_DIR }}
