name: Deploy Angular App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          # Use the empty string ("") to ignore status or conclusion in the search
          workflow_conclusion: success
          # Optional, no need to specify if PR is
          commit: ${{github.event.pull_request.head.sha}}
          # Optional, will use the specified branch. Defaults to all branches
          branch: master
          name: pmb-artifacts
          # Optional, name is treated as a regular expression if set true
          name_is_regexp: true
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: pmb-artifacts

      - name: SCP Command to Transfer Files
        # You may pin to the exact commit or the version.
        # uses: appleboy/scp-action@8a92fcdb1eb4ffbf538b2fa286739760aac8a95b
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          # ssh port
          port: ${{ secrets.DESTINATION_PORT }}
          # ssh username
          username: ${{ secrets.DEPLOYER_USER }}
          # ssh password
          password: ${{ secrets.DEPLOYER_PW }}
          source: pmb-artifacts
          target: ${{ secrets.DESTINATION_TMP_DIR }}
